adj: 1.0e-06
cosine_gex: 0.001
cosine_pex: 0.001
delta: 0.001
dropout: 0.0
epochs: 2000
kl_gex: 1.0e-06
kl_pex: 1.0e-06
latent_dim: 64
lr: 0.002
model: model_Breast_2023_11_02_00_08.pth
mutual_gex: 0.001
mutual_pex: 0.001
ngenes: 3026
nproteins: 30
nspots: 4169
patience: 1000
proteins:
- CD163
- CR2
- PCNA
- VIM
- KRT5
- CD68
- CEACAM8
- PTPRC_1
- PAX5
- SDC1
- PTPRC_2
- CD8A
- BCL2
- CD19
- PDCD1
- ACTA2
- FCGR3A
- ITGAX
- CXCR5
- EPCAM
- MS4A1
- CD3E
- CD14
- CD40
- PECAM1
- CD4
- ITGAM
- CD27
- CCR7
- CD274
recons_gex: 0.001
recons_pex: 0.001
spatial: 1.0e-05
tissue: Breast
wd: 0.0
